name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore -f net6.0-ios

    - name: Archive Artifacts
      run: |
        mkdir artifacts
        mv path/to/your/app/file artifacts/
      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: App
        path: artifacts/
